#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jackson-parent
Version  : 2.6.1
Release  : 3
URL      : https://github.com/FasterXML/jackson-parent/archive/jackson-parent-2.6.1.tar.gz
Source0  : https://github.com/FasterXML/jackson-parent/archive/jackson-parent-2.6.1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.6.1/jackson-parent-2.6.1.pom
Source2  : https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.6.2/jackson-parent-2.6.2.pom
Source3  : https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.7/jackson-parent-2.7.pom
Source4  : https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8.pom
Source5  : https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.9.1/jackson-parent-2.9.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jackson-parent-data = %{version}-%{release}

%description
jackson-parent
==============
Project for parent pom for all Jackson components

%package data
Summary: data components for the mvn-jackson-parent package.
Group: Data

%description data
data components for the mvn-jackson-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.6.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.6.1/jackson-parent-2.6.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.6.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.6.2/jackson-parent-2.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.7/jackson-parent-2.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.9.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.9.1/jackson-parent-2.9.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.6.1/jackson-parent-2.6.1.pom
/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.6.2/jackson-parent-2.6.2.pom
/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.7/jackson-parent-2.7.pom
/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.8/jackson-parent-2.8.pom
/usr/share/java/.m2/repository/com/fasterxml/jackson/jackson-parent/2.9.1/jackson-parent-2.9.1.pom
